- name: mysql install
  apt: name={{ item }} state=installed
  with_items: mysql_install_list

- name: mysql runnning and enabled
  service: name=mysql state=running enabled=yes


- name: Create database
  mysql_db: db={{ dbname }} state=present encoding=utf8


- name: Create database user
  mysql_user: >
    name={{ dbuser }}
    password={{ dbpassword }}
    priv={{ dbname }}.*:ALL
    state=present

- name: wordpress download
  get_url: url="http://wordpress.org/latest.tar.gz" dest=/usr/share/nginx/html/


- name: un compress tar file
  command: chdir=/usr/share/nginx/html/ tar xvzf latest.tar.gz 

- name: make uploads contents directory
  file: path=/usr/share/nginx/html/wordpress/wp-content/uploads state=directory 

- name: change owner wordpress
  file: path=/usr/share/nginx/html/wordpress/ state=directory recurse=yes owner=www-data group=www-data 

- name: copy config file   
  shell: creates=/usr/share/nginx/html/wordpress/wp-config.php cp /usr/share/nginx/html/wordpress/wp-config-sample.php /usr/share/nginx/html/wordpress/wp-config.php 

- name: set DB_NAME
  replace: dest=/usr/share/nginx/html/wordpress/wp-config.php regexp='database_name_here' replace='{{ dbname }}' backup=yes

- name: set DB_USER
  replace: dest=/usr/share/nginx/html/wordpress/wp-config.php regexp='username_here' replace='{{ dbuser }}' backup=yes

- name: set DB_PASSWORD
  replace: dest=/usr/share/nginx/html/wordpress/wp-config.php regexp='password_here' replace='{{ dbpassword }}' backup=yes
